[package]
authors = ["M-Labs"]
name = "unwind_backtrace"
version = "0.0.0"
edition = "2018"

[lib]
name = "unwind_backtrace"
path = "lib.rs"

[dependencies]
unwind = { path = "../libunwind" }
libc = { path = "../libc" }
